name: DocFX Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: Install dependencies
        run: dotnet restore ${{ github.workspace }}/DocFX/DemoWebApi/DemoWebApi.sln
      - name: DocFX Build
        working-directory: docs
        run: docfx ${{ github.workspace }}/DocFX/DemoWebApi/docfx_project/docfx.json
        continue-on-error: false
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
